[build]
  command = "npm run build" # Commande de construction de votre projet
  publish = "Cadeau/dist" # Dossier à publier sur Netlify (peut être 'dist', 'public', ou autre selon votre configuration)
